### ISSUE TITLE
Move from deprecated routes to redirects/rewrites

### ISSUE THREAD

**Issue by frontsideair** [universse/gatsby-plugin-now#5] opened 2021-09-05 10:49 UTC
Vercel docs indicate that `routes` are [now considered legacy](https://vercel.com/docs/cli#project-configuration/routes), and by my testing Gatsby [splat redirects](https://support.gatsbyjs.com/hc/en-us/articles/1500003051241-Working-with-Redirects) don't work with `routes` regex.

I believe switching to redirects/rewrites will fix splats too.

**Comment by phuoccss** [comment] 2021-09-06 08:36
Hi, thanks for the heads-up.

Vercel itself is using [routes](https://github.com/vercel/vercel/blob/main/packages/frameworks/src/frameworks.ts#L145-L191) to handle Gatsby's redirects and rewrites. So unless Vercel switches to `redirects` and `rewrites`, there's nothing I can do.

Regarding splat, my plugin already converts Gatsby splat to Vercel routes-compatible format. It wouldn't work if you use Gatsby splat as is in `vercel.json`. Could you give a reproduction where it doesn't work as expected?

**Comment by frontsideair** [comment] 2021-09-06 09:26
You're completely right, I didn't come across how Vercel handles Gatsby when I was researching.

In my case, I used [this syntax](https://github.com/frontsideair/blog/commit/31812c73a3a44f19d9319f81ed5e74a7ab2b954f#diff-fddc92c51ddda723ee5bb30f3de317002e65e9721079c0c4d748431bf2efa2b0), which seems to be [supported by Gatsby](https://support.gatsbyjs.com/hc/en-us/articles/1500003051241-Working-with-Redirects). The generated redirects file doesn't seem to be changing the splats:

```
{"src":"/_hive/*","dest":"https://hive.splitbee.io/*"}
```

And when I deployed, I was getting 404 for this route. I think the [deployment](https://blog-qw1infxpl-frontsideair.vercel.app) is still around. (Something to note, it returns a 401 when it's successful since the domain doesn't match the one set up for the analytics.)

When I browse the code, it seems like the only place a regex replace is performed is for the pages. Maybe this is the issue?

**Comment by phuoccss** [comment] 2021-09-06 13:34
I see. Currently, I only handle the splat for client-only routes.

Anw, looks like the equivalent for Vercel is

```json
{
  "routes": [
    {
      "src": "/_hive/(.*)",
      "dest": "https://hive.splitbee.io/$1"
    }
  ]
}
```

This is the simplest use case  and I can make the plugin compatible with the Gatsby cloud's splat redirects.

However, it won't work for more complicated setup with many capture groups, which Vercel supports. For eg,

```json
{
  "routes": [
    {
      "src": "/_hive/(.*)/(.*)",
      "dest": "https://hive.splitbee.io/$2/$1"
    }
  ]
}
```

So I'm thinking of introducing a plugin option that allows adding of custom rules to the generated redirects file. But it's probably not worth complicating the code since it seems to be an unlikely use case. And I'm not sure on how Gatsby handles this scenario via `createRedirect`. What do you think?

**Comment by frontsideair** [comment] 2021-09-07 07:26
I think the best approach would be to support only what Gatsby supports, which a single splat. Gatsby may support multiple splats, which I haven't checked, but since it's not documented doesn't seem like it's worth spending time on and complicating the code and the plugin API. (I may be biased because that would solve my use case.)

If someone needs more complicated redirects, I think they should ask Gatsby to support (or document) them, then this plugin can enable this. Otherwise going with a `vercel.json` would be a better option.

**Comment by phuoccss** [comment] 2021-09-07 12:40
Yup, that makes sense. Will push a new version soon.

**Comment by phuoccss** [comment] 2021-09-07 14:30
I just published a beta version `gatsby-plugin-zeit-now@beta`. Could you give it a try?

Just a note, since you want rewrites instead of redirects, you need to supply a status code of 200 as well.

**Comment by frontsideair** [comment] 2021-09-08 07:19
Just tried, the generated route file seems correct and it's behaving as it should, thanks!. Also thanks for the heads up, I'm adding 200 in `gatsby-node.js`.

**Comment by phuoccss** [comment] 2021-09-09 03:47
Cool. I will wait a while first before making a stable release. Meanwhile, please let me know if you come across any bug. Thanks a lot.

**Comment by frontsideair** [comment] 2021-10-16 20:41
It's working without any hiccups for me, wanted to let you know. 😄

**Comment by phuoccss** [comment] 2021-10-30 08:07
Thanks for trying it out 😁. I've just released a stable version. Guess I can close this issue now.

**Closed as completed by phuoccss** 2021-10-30 08:07 UTC
